# Generated by Django 3.1.7 on 2021-11-10 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите Название Праздника', max_length=15, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Введите дату', verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Ваше желание', verbose_name='Желание')),
                ('description', models.TextField(help_text='Введите описание желания', verbose_name='Описание')),
                ('website', models.URLField(blank=True, help_text='Скопируйте ссылку на желание', null=True, verbose_name='Ссылка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.group')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
